### ISSUE TITLE
programming-beginner/6.comparsions/3.1.re (5, 6)

### ISSUE THREAD

**Issue by MultyPony** [Paqmind/platform#1]
[Comparisons(5, 6)](http://paqmind.com/courses/programming-beginner/6.comparisons/challenges/3.1.re/)
`x > 10 && 5 > x`
It's more readable this way:
`5 < x && x < 10`
_It's readable, but the meaning is different._
`x > a && x > b && x > c`
_There is no `c` at the begining_

**Comment by ivan-kleshnin** [comment]
Confirmed.

5. should have been: `x < 10 && 5 > x`, fixed.
6. fixed.
