### ISSUE TITLE
fp-beginner/1.intro/exercises/1.0.qz/

### ISSUE THREAD

**Issue by alexpanchuk** [Paqmind/platform#14]
[link](http://paqmind.com/courses/fp-beginner/1.intro/exercises/1.0.qz/)

Calls 5 is wrong (doesn't resolve 3).
```js
((x, y) => x(2) + y)(((x, y) => x)(1), 2)
((x, y) => x(2) + y)(1, 2) // in solution ((x, y) => x(2) + y)((_ => 1), 2)
x is not a function
```
probably it's a typo and was meant
```js
((x, y) => x(2) + y)((x => y => x)(1), 2)
```

**Comment by ivan-kleshnin** [comment]
Yes. I treated functions as curried where they aren't.

**Comment by ivan-kleshnin** [comment]
Fixed in the next release.
