### ISSUE TITLE
Hyperlink issue on homepage

### ISSUE THREAD

**Issue by gopalindians** [Paqmind/platform#17]
### On the [home page](https://paqmind.com/) in the 3rd paragraph there is a hyperlink named as links which is pointing to [https://localhost:8080/links/](https://localhost:8080/links/)  it should point to [https://paqmind.com/links/](https://paqmind.com/links/)

_See the image for reference_
![learning platform for programmers and web developers](https://user-images.githubusercontent.com/1937433/43242775-90c83e1e-90c0-11e8-9b87-65f7e120a9b8.png)

**Comment by ivan-kleshnin** [comment]
Indeed. Thanks for reporting, we'll fix that soon. 👍

**Comment by ivan-kleshnin** [comment]
Fixed.
