### ISSUE TITLE
Typos in callbacks/1

### ISSUE THREAD

**Issue by ivan-kleshnin** [Paqmind/platform#18]
@Богдан Богдан

Hello, 
Спасибо за проект, но тут реально, 

#### Issue 1

`(x) => (x, console.log(x))` - сама функция не возвращает значение

```
> const a = (x) => (x, console.log(x))
console.log(a(5))
```

`5` - Это просто действие функции, к примеру вывести на консоль.
`undefined` - а это возвращаемое значение функции.

На сайте это считает не callback, хотя это callback

####  Issue 2

```
const a = (x) => () => { fn(x * 2) }
console.log(a(5)); //[Function]
```

- здесь функция возвращает значения, поэтому callback не является.

**Comment by ivan-kleshnin** [comment]
Thanks for reporting! English please ;)

> (x) => (x, console.log(x)) - сама функция не возвращает значение

Yes, we have a typo here.

```
(x) => (x, console.log(x))
```

should be:

```
(x) => (console.log(x), x)
```

(or the answer should be different).

> (x) => () => { fn(x * 2) } - здесь функция возвращает значения, поэтому callback не является.

As I replied there, it depends on the number of calls. Curried functions are equivalent to multi-argument functions (logically) so your example:

```
const a = (x) => () => { fn(x * 2) }
console.log(a(5)) //[Function]
```

can be rewritten as

```
console.log(a(5)()) // undefined
```

to "match the answer". And, as I said, I consider it to be a description problem so it will be updated.

**Comment by boggddan** [comment]
Thank you for you reply.

**Comment by ivan-kleshnin** [comment]
Fixed.
