### ISSUE TITLE
Hyperlink issue in footer

### ISSUE THREAD

**Issue by dmitrij-schmidt** [Paqmind/platform#22]
All of the links in footer, Tutorials section, lead to #200 errors. Most probably their targets were renamed in the process.

Overall, whole section might be revisited, since there are too many tutorials to fit in without breaking the layout.

**Comment by ivan-kleshnin** [comment]
> Overall, whole section might be revisited, since there are too many tutorials to fit in without breaking the layout.

Yes, absolutely. The site is in alpha stage so there're many errors like that :(

**Comment by ivan-kleshnin** [comment]
Fixed in dev. Thanks for reporting!
