### ISSUE TITLE
/team path issue

### ISSUE THREAD

**Issue by dmitrij-schmidt** [Paqmind/platform#23]
All of the URLs within `https://paqmind.com/en/team*` path are throwing #200 error.

They are included within:

1. "Project/About" element within footer across the website

2. [homepage](https://paqmind.com/en)
> Want to ask or propose us something? Use the Team page for that.

3. [Credits](https://paqmind.com/en/credits)
"Platform Development" and "Content" sections

**Comment by ivan-kleshnin** [comment]
Fixed in dev.
