### ISSUE TITLE
Course duration mismatch in React Fundamentals

### ISSUE THREAD

**Issue by dmitrij-schmidt** [Paqmind/platform#24]
There is misguiding mismatch between course duration in course description:
>Master React in 4 weeks

and a label to the icon below that states:

>7 weeks

Amount of 7 weeks is probably incorrect, since [full course description](https://paqmind.com/en/courses/react-I) suggests 4 weeks as course duration.

**Comment by ivan-kleshnin** [comment]
Hi Dmitry. You're right "7 weeks" label is wrong. Thanks for reporting!

**Comment by ivan-kleshnin** [comment]
Fixed in dev.
