### ISSUE TITLE
Broken Link 'FP with Ramda'

### ISSUE THREAD

**Issue by gitMonks** [Paqmind/platform#25]
Hi 

First of all thank you for creating this learning resource. Secondly, the start link for the FP with Ramda is broken i.e error code 200:

https://paqmind.com/en/tutorials/ramda-I/challenges/0.1.qzn

Can you please fix it.

Thanks
Imran

**Comment by ivan-kleshnin** [comment]
Thanks for reporting @gitMonks! It's fixed now.

The site is going through massive changes and we don't have enough resources to verify each step properly. Any feedback like this is highly appreciated.
